version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRESQL_DATABASE: 'graduate-system'
      POSTGRESQL_USER: 'postgres'
      POSTGRESQL_PASSWORD: 'postgres'
    ports:
      - '3030:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  internship-storage:
