version: '3'

services:
  graduate-system-be:
    image: graduate-system:latest
    ports:
      - '8080:8080'
    depends_on:
      - graduate-system-db
  graduate-system-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRESQL_DATABASE: 'graduate-system'
      POSTGRESQL_USER: 'postgres'
      POSTGRESQL_PASSWORD: 'postgres'
    ports:
      - '3030:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
